[package]
name = "believer"
version = "0.1.4"
authors = ["Maxime Tremblay"]
edition = "2018"
description = "A toolbox to simulate error correcting code performance."
license = "MIT OR Apache-2.0"

[dependencies]
num = "0.2.0"
rand = "0.7.0"
itertools = "0.8.0"
rayon = "1.2.0"


