[package]
name = "believer"
version = "0.2.0"
authors = ["Maxime Tremblay"]
edition = "2018"
description = "A toolbox to simulate error correcting code performance."
license = "MIT OR Apache-2.0"

[dependencies]
num = "0.2.0"
rand = "0.7"
rand_chacha = "0.2"
itertools = "0.8"
rayon = "1.2"

